### ISSUE TITLE
Error on stable channel

### ISSUE THREAD

**Issue by susilolab** [SergioBenitez/yansi#1]
How to fix this problem?. this error occured when i try to install rocket

error[E0554]: #[feature] may not be used on the stable release channel
 --> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/yansi-0.3.3/src/lib.rs:1:32
  |
1 | #![cfg_attr(feature="nightly", feature(const_fn))]
  |                                ^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `yansi`.
Build failed, waiting for other jobs to finish...
error: build failed

thanks

**Comment by SergioBenitez** [comment]
Using the "nightly" feature requires you to be using a nightly compiler. Unless you need to be able to disable on the fly, you shouldn't need the feature.

**Comment by susilolab** [comment]
thannks, i'll switch to rust nightly
