### ISSUE TITLE
Bright colors?

### ISSUE THREAD

**Issue by dbeckwith** [SergioBenitez/yansi#12]
Is there any way to do the ["bright" colors](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) specified by codes 90-97 (foreground) and 100-107 (background)?

**Comment by SergioBenitez** [comment]
I'm fairly certain we call that "bold". Give it a shot.

**Comment by dbeckwith** [comment]
"Bold" and "bright" are different things. Sometimes they are implemented the same way but usually not. See for yourself with this:
```bash
printf \
'\x1b[31mESC[31m: red\x1b[m\n'\
'\x1b[1;31mESC[1;31m: red bold\x1b[m\n'\
'\x1b[91mESC[91m: bright red\x1b[m\n'\
'\x1b[1;91mESC[1;91m: bright red bold\x1bm\n'
```
![image](https://user-images.githubusercontent.com/1279939/108711533-7e485580-74e3-11eb-8c8e-19ea0b60b57c.png)

**Comment by SergioBenitez** [comment]
Ah, I see, this is not a standard sequence. This isn't an option but it would be simple to add. Feel free to send a PR. The docs should note that this is non-standard and the caveats this implies (ie, what happens if the terminal doesn't support them?).

**Comment by dbeckwith** [comment]
Is it non-standard? I thought it was very common so I assumed it was standard. Genuinely curious, what source do you have for that?
