### ISSUE TITLE
API to constrain a `Style` from truecolor to basic colors

### ISSUE THREAD

**Issue by epage** [SergioBenitez/yansi#15]
This would allow someone to write their `Style`s assuming truecolor and then auto-convert to best match for what the terminal supports

[wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) has some RGB values for 3-bit colors, we could write an algorithm to do a best-match from RGB values to those 3-bit values.

**Comment by SergioBenitez** [comment]
Can we reliable detect truecolor support? I think that would be a nice fallback.

**Comment by epage** [comment]
I would expect detection would be left to a policy piece, like in #18 and that this would just be an API that users can optionally call, based on that policy piece.

**Comment by SergioBenitez** [comment]
I think the best approach is to leave this to the consumer entirely, given that there's no reliable mechanism, as far as I can tell, to detect true-color support. With `v2` (and `v1` as well. albeit not as concisely), you can do something like:

```rust
use yansi::Paint;

fn truecolor_or(fallback: Color, r: u8, g: u8, b: u8) -> Color {
    match supports_truecolor() {
        true => Color::Rgb(r, g, b),
        false => fallback,
    }
}

println!("{}", "try it".fg(truecolor_or(Color::Red, 244, 200, 212)));
```

You can even implement a `Paint`-like extension trait to make `truecolor_or` a method of every type, or whatever API you'd like.
