### ISSUE TITLE
Add hyperlink style support

### ISSUE THREAD

**Issue by epage** [SergioBenitez/yansi#19]
See https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

**Comment by SergioBenitez** [comment]
I'm generally in favor, but there's a backwards compatibility issue. From the gist:

> Any terminal that correctly implements OSC parsing according to ECMA-48 is guaranteed not to suffer from compatibility issues. That is, even if explicit hyperlinks aren't supported, the target URI is silently ignored and the supposed-to-be-visible text is displayed, without artifacts.

Here's the problem: imagine a builder method that lets you set a link on a `Paint`:

```rust
println!("Visit our {}", Paint::new("docs").link("https://api.rocket.rs"));
```

On terminals that support links, they'll see:

> Visit our [docs](https://api.rocket.rs).

But terminals that don't support links will see:

> Visit our docs.

That is, the link is completely lost.

There is also this:

> At this moment, terminals known to be buggy (OSC 8 resulting in display corruption) are VTE versions up to 0.46.2 and 0.48.1, Windows Terminal up to 0.9, Emacs's built-in terminal, and screen with 700+ character long URLs.

So, to be safe, we'd need to conservatively detect whether the terminal supports hyperlinks. [This project](https://github.com/jamestalmage/supports-hyperlinks) seems to do it, but it's not clear to me how correct or reliable it is. We should have no false positives; false negatives are okay.

We should have a `Paint::supports_hyperlinks()` and `Paint:enable_hyperlinks(bool)`, or some version of these APIs, to force detect/force-enable/force-disable hyperlink support.

**Comment by epage** [comment]
`yansi` today seems to be just mechanism of painting, leaving the policy of what's supported to elsewhere (see #18).  As long as we provide a way for users to disable coloring, I see it as the user's decision for how accurate the detection needs to be.

**Comment by SergioBenitez** [comment]
Alright, I think if we disable displaying hyperlinks by default and have a toggle for enabling them, my concerns are resolved. This is the inverse of what we do for coloring, which makes sense given the differences I've alluded to above.

**Comment by epage** [comment]
>  I suppose the reason I see such a difference between "can I use colors?" and "can I use hyperlinks?" is that the former has pretty reasonable answers in "is it a TTY? then yes!". 

That isn't true for true color but `yansi` supports that.

**Comment by SergioBenitez** [comment]
The `v2` branch now has experimental hyperlinking support.
