### ISSUE TITLE
Console coloring is not working in Windows 7

### ISSUE THREAD

**Issue by zoumi** [SergioBenitez/yansi#2]
My system info:
Microsoft Windows 7 Ultimate 64bit

Rust info:
nightly-i686-pc-windows-gnu (default)
rustc 1.21.0-nightly (f774bced5 2017-08-12)

Cargo.toml:
yansi = "0.3.3"

main.rs:
Paint::enable_windows_ascii();
print!("{} light, {} light!",            
           Paint::green("Green"), 
           Paint::red("red").underline());

console output:

![vhh](https://user-images.githubusercontent.com/5162901/30113510-873ae59e-9347-11e7-8baa-c2986e254fbc.JPG)

**Comment by zoumi** [comment]
Is similar with:
https://github.com/SergioBenitez/Rocket/issues/363

**Comment by SergioBenitez** [comment]
As mentioned in the [documentation](https://docs.rs/yansi/0.3.3/yansi/#windows), Windows only supports ASCII coloring on versions beginning with the Windows 10 anniversary update. This does not include Windows 7. There are no plans for this library to support console coloring on versions before the Windows 10 anniversary update.
