### ISSUE TITLE
Used parking_lot version is quite old

### ISSUE THREAD

**Issue by janbaudisch** [SergioBenitez/yansi#34]
Yansi uses `parking_lot` version 0.5, which is over 3 years old. Would it be possible to update it? I can see that the last update to `Cargo.toml` was a version bump, so I don't know if it would need to wait for something else?

**Comment by dkg** [comment]
The dev-dependency only uses `parking_lot` for `parking_lot::Mutex`. 

I looked into just updating `parking_lot` to use 0.11 and the test suite for yansi 0.5.0 failed with this error:

```
error[E0015]: calls in statics are limited to constant functions, tuple structs and tuple variants
 --> src/tests.rs:8:26
  |
8 | static LOCK: Mutex<()> = Mutex::new(());
  |                          ^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0015`.
warning: `yansi` (lib test) generated 4 warnings
error: could not compile `yansi` due to previous error; 4 warnings emitted
```

It looks to me like `src/tests.rs` is trying to use the `LOCK` object to ensure that parallelized tests don't clobber each other.

https://github.com/rust-lang/rust/issues/43155 suggests that using the [serial_test crate](https://crates.io/crates/serial_test) might be a cleaner way to go

**Comment by nnethercote** [comment]
Unfortunately it looks like this repo hasn't been touched in almost three years. It seems to be dead :(

**Comment by SergioBenitez** [comment]
It's not dead.

**Comment by nnethercote** [comment]
Sorry, my mistake! I thought it was dead because there haven't been any releases or commits for almost 3 years, and there are some seemingly mergeable PRs from May 2021 sitting open. I'm glad to hear it's still alive, especially given that it often gets over 10,000 downloads per day from crates.io 😄
