### ISSUE TITLE
incorrect link to docs

### ISSUE THREAD

**Issue by Anton-4** [SergioBenitez/yansi#4]
The link in the readme to the documentation goes to https://docs.rs/yansi/0.3.4/yansi/ ,
the resulting page says: "The requested resource does not exist"

**Comment by SergioBenitez** [comment]
docs.rs is running an outdated version of rustc resulting in failed compilation and the 404 that you see. I've pinged @onur but have received no response. Unfortunately there's no way to upload docs to docs.rs manually.

**Comment by Anton-4** [comment]
So be it, thanks for looking into it :)

**Comment by SergioBenitez** [comment]
While that's getting fixed, you can use the last rendered docs: https://docs.rs/yansi/0.3.3/yansi/. Everything remains the same between `0.3.3` and `0.3.4`.

**Comment by SergioBenitez** [comment]
Fixed upstream!
