### ISSUE TITLE
The method `Paint::clear` breaks the project when using `String.clear`

### ISSUE THREAD

**Issue by rsalmei** [SergioBenitez/yansi#45]
Hi,
I've seen #42 where `clear` simply was not called for a Vector.
But I'm using `String.clear()` and it is worse because it breaks the project, it won't compile anymore.
The project is ready, it does compile, but if I `use yansi::Paint`:

```
warning: use of deprecated method `yansi::Paint::clear`: renamed to `resetting()` due to conflicts with `Vec::clear()`.
         The `clear()` method will be removed in a future release.
   --> src/rename.rs:114:64
    |
114 |                     false => g.iter_mut().for_each(|m| m.wname.clear()),
    |                                                                ^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

error[E0308]: mismatched types
   --> src/rename.rs:114:56
    |
114 |                     false => g.iter_mut().for_each(|m| m.wname.clear()),
    |                                                        ^^^^^^^^^^^^^^^ expected `()`, found `Painted<&String>`
    |
    = note: expected unit type `()`
                  found struct `Painted<&std::string::String>`
help: consider using a semicolon here
    |
114 |                     false => g.iter_mut().for_each(|m| { m.wname.clear(); }),
    |                                                        +                +++

warning: use of deprecated method `yansi::Paint::clear`: renamed to `resetting()` due to conflicts with `Vec::clear()`.
         The `clear()` method will be removed in a future release.
   --> src/rename.rs:119:51
    |
119 | ...                   .for_each(|m| m.wname.clear());
    |                                             ^^^^^

error[E0308]: mismatched types
   --> src/rename.rs:119:43
    |
119 | ...                   .for_each(|m| m.wname.clear());
    |                                     ^^^^^^^^^^^^^^^ expected `()`, found `Painted<&String>`
    |
    = note: expected unit type `()`
                  found struct `Painted<&std::string::String>`
help: consider using a semicolon here
    |
119 |                             .for_each(|m| { m.wname.clear(); });
    |                                           +                +++

For more information about this error, try `rustc --explain E0308`.
```

What could I do?

**Comment by SergioBenitez** [comment]
A few things. First, you could import `Paint` only in the scope that you actually use it. You could alternatively limit your use of yansi to a single module, so it doesn't infect unrelated code. In either case, this limits the scope of the trait methods.

Alternatively, you could call the `String` method using the full syntax: `String::clear(..)`. This removes the ambiguity.

**Comment by rsalmei** [comment]
I see, thank you.
I can try that, but if you excuse me saying it, what an oversight, hum?
Did you really implement a `.clear(&self)` for any `T`? So it broke all `.clear()` methods anywhere in `std` and beyond?
<img width="445" alt="image" src="https://github.com/user-attachments/assets/6c64ab20-cf91-44b6-ab99-37e20828d06c">

**Comment by SergioBenitez** [comment]
> I can try that, but if you excuse me saying it, what an oversight, hum?

It's a bit trickier than a trivial oversight. As I mentioned in the other post:

> Fascinating. Rust is selecting the Paint::clear() method before the Vec::clear() method because the former takes an &self as a receiver and the latter an &mut self, despite the latter being an inherent method.

In my opinion, this behavior is _really_ surprising, to the point that I wouldn't have believed it after over a decade of programming in and conducting research on Rust. And it's not just me - this behavior was debated several times by the core Rust team, and even the language reference itself calls it out as surprising.

> Did you really implement a .clear(&self) for any T?

Yes.

> So it broke all .clear() methods anywhere in std and beyond?

No. This is only a concern when both `Paint` and an inherent method that doesn't take `&self` are in scope. If either of those things isn't true, there's no problem.
