### ISSUE TITLE
Automatic disabling when stdout/stderr is not a terminal.

### ISSUE THREAD

**Issue by sbstp** [SergioBenitez/yansi#7]
`Paint::auto_disable_stdout` would disable color if stdout is a terminal, `Paint::auto_disable_stderr` would disable color if stderr is a terminal. The [atty](http://lessis.me/atty/atty/index.html) library could be used to do it easily.

**Comment by SergioBenitez** [comment]
It's _really_ trivial to do this yourself. I don't think it's worth `yansi` taking on a dependency to provide such simple functionality.
